language: java
python: "3.6"

before_deploy:
  # pip3 not found in travis... for some reason
  - sudo apt-get update
  - sudo apt-get install python3-pip
  # run the docs
  - cd docs
  - pip3 install --user -r requirements.txt
  - python3 generate_docs.py
  # file to tell GitHub pages not to try to run jekyll stuff (can break urls)
  - touch output/.nojekyll

deploy:
  provider: pages
  skip-cleanup: true
  local-dir: docs/output
  github-token: $GH_TOKEN
  on:
    branch: master
